### ISSUE TITLE
Improve responsiveness with big JSON files

### ISSUE THREAD

**Issue by bjesuiter** [zgrossbart/jdd#12]
I have fairly big Json Files with a lot of sensor measurement data , that i need to compare. 

Unfortunately, the comparison blocks the main thread for so long, that chrome thinks, the website has crashed. 

2 Solutions: 
- Send the JSON content to a server for diffing - maybe not wanted due to privacy and cost issues
- Use a WebWorker - Makes Browser Client Multi-threaded Workloads possible and is supported by ALL major browsers now (even IE/ Edge!) - see https://caniuse.com/#search=webworker

**Comment by bjesuiter** [comment]
With a WebWorker, you could even give some progress response. 
At least you can show, that the site is working, at best you could show a progress bar! 🥇

**Comment by zgrossbart** [comment]
Thank you for the suggestion.  I have looked into web workers, but I don't think they would offer much improvement on the overall performance and they would complicate the application.

JSONDiff is a browser based tool and all of the compare runs in the browser.  The advantages are a very fast load time and a super fast compare for smaller documents.  The disadvantage is that there's a size limit to the types of compare we can do.

The best solution for this is probably to create a NodeJS based version of this tool.  That would make it possible to take advantage of a faster runtime environment and better threading support.  

I don't have time for that project right now, but you're welcome to take a look.

Thanks,
Zack
