### ISSUE TITLE
Update the copyright year

### ISSUE THREAD

**Issue by alator21** [zgrossbart/jdd#34]

**Comment by zgrossbart** [comment]
Can you please give me some more details.  Would you like me to update the copyright year of the source code?  Somewhere else?  I haven't made any changes in 2020 yet.

**Comment by alator21** [comment]
Hi, @zgrossbart. I refer to the source code(jdd.js)

**Comment by zgrossbart** [comment]
Thank you for the clarification and thank you for the issue.  I'll update the copyright in the source code when I make a change in 2020.
