### ISSUE TITLE
Query String Parameters

### ISSUE THREAD

**Issue by peternewman** [zgrossbart/jdd#38]
The second way is to add parameters to the URL like this:

http://jsondiff.com/?left=http://jsondiff.com/one.json&right=http://jsondiff.com/two.json
_Originally posted by @zgrossbart in https://github.com/zgrossbart/jdd/issues/10#issuecomment-306167117_

I came here to try and find out about this and thankfully found this in a closed issue eventually. It would be great if this was better signposted, ideally on the webpage somewhere or at least in the README.

Perhaps with the stereotypical share button if both sides are URLs? I assume you'll hit get query string limits if they're raw text.

**Comment by zgrossbart** [comment]
Good idea @peternewman.  Thank you.  I've added this to the readme.

**Comment by peternewman** [comment]
Great thanks @zgrossbart !
