### ISSUE TITLE
THIS IS AMAZING

### ISSUE THREAD

**Issue by bf4** [zgrossbart/jdd#41]
I'm consuming an API with a super complex response body and was writing an email to the supplier asking about a change in it, and I installed jdd and ran it and it ran and it was fast and looked great!

e.g.

<img width="1709" alt="Screen Shot 2022-01-21 at 9 07 52 AM" src="https://user-images.githubusercontent.com/142914/150550444-99b8205e-fa87-4108-9ff2-14caadefb266.png">

Thanks for your great work.

**Comment by zgrossbart** [comment]
Thank you @bf4.  I'm really happy that JSONDiff was able to help you.
