### ISSUE TITLE
web app getting hanged for very large files

### ISSUE THREAD

**Issue by bansalnitin92** [zgrossbart/jdd#43]
Awesome App !! made my life easy :D

Just One issue: web app getting hung for very large files

tried both http://www.jsondiff.com/ and on local host as well. 
The browser stopped responding after uploading and clicking on Compare button. can not upload the file as it contains sensitive info

**Comment by zgrossbart** [comment]
Thank you for using the app.  

How large are your very large files?  At some point the browser will simply run out of memory.  You can try allocating more memory to your browser when you start it or try a different browser (Chrome has been the best for me), but eventually the file will just be too big.

**Comment by graphcon** [comment]
Since OP didn't post another I reply, I have one idea:
Would it be possible to run your diff on command line on a NodeJS environment with a file as output? It might resolve the memory issue as NodeJS is better configurable than a browser.

**Comment by zgrossbart** [comment]
Thanks for the idea @graphcon.  Right now JSONDiff depends on the browser so you can't run it as a command line tool in NodeJS, but there are some other diff tools written specifically for NodeJS.

**Comment by graphcon** [comment]
Oh great, I will check those out. Thanks
