### ISSUE TITLE
When running from Docker container, auto-loading of JSON does not work

### ISSUE THREAD

**Issue by greg-cacheq** [zgrossbart/jdd#44]
To reproduce:
1) run jdd in Docker
2) try URL http://localhost/left=http://jsondiff.com/one.json&right=http://jsondiff.com/two.json

Expected result:
- The contents of one.json and two.json will be compared

Actual result:
- File names instead of file contents appear in left and right panels
- Compare progress meter is shown and never finishes
<img width="1670" alt="Screen Shot 2022-02-15 at 09 26 48" src="https://user-images.githubusercontent.com/36746958/154105009-29d014de-c29b-4c25-88a8-b03a31d1f1aa.png">

**Comment by zgrossbart** [comment]
There was an error in the README when running the Docker file.  I've updated it.  Make sure you run the following commands to make sure everything is cleaned up:

```bash
docker stop jdd
docker rm jdd
docker build --tag=jdd:v1-alpine --file=Dockerfile.alpine .
docker run -i --name jdd -p 127.0.0.1:8080:80/tcp jdd:v1-alpine
```

Then you have to make sure your URL is formatted properly.  It should look like this:

http://localhost:8080/?left=http://jsondiff.com/one.json&right=http://jsondiff.com/two.json

**Comment by zgrossbart** [comment]
<img width="1376" alt="image" src="https://user-images.githubusercontent.com/664044/154154018-bbcce0c7-6055-4898-9eda-6946c549d387.png">
