### ISSUE TITLE
Maintain all object differences in same level

### ISSUE THREAD

**Issue by krishnaraman001** [zgrossbart/jdd#46]
Can we compare objects on both sides within same level like below image
![image](https://user-images.githubusercontent.com/28945373/161718986-b5dcc9a7-7fa3-4a76-a157-2a8d35673644.png)
Is it possible to do like that by doing some changes?

If objects are of different sizes, then heights of JSONS will be different and while rendering u can see like
![image](https://user-images.githubusercontent.com/28945373/161719609-3868c84e-14a5-4b0e-be59-f68795ec2ca0.png)

**Comment by krishnaraman001** [comment]
HI @zgrossbart  this is really an awesome tool. we are using for comparison which really helps a lot.

My requirement is to maintain all the differences in same level on both sides similar to visual studio code, so it will be very easy the data easily with out scrolling up and down if JSONS are of different length.

is it possible to do that by doing changes in the code?

**Comment by zgrossbart** [comment]
Hello @krishnaraman001.  I tried that style of diff when I was first creating the tool.  It worked well when comparing two JSON documents that were short and almost the same content, but it didn't scale very well.  When the JSON documents were either very long or very different the results were difficult to read.  

It would be possible to do this kind of view with a code change, but the code change would be very large.

**Comment by krishnaraman001** [comment]
Hi @zgrossbart Thank you so much for the response.

I need that requirement for our application. we are trying to integrate this JDD application. If possible can i have those code changes that you have done initially. please suggest me an approach to fulfill that requirement.

**Comment by zgrossbart** [comment]
Hello @krishnaraman001,

I'm sorry, but my original code changes were very preliminary and wouldn't be useful with the current JSONDiff code base.  What you're looking for would need to be a separate project.
