### ISSUE TITLE
Push Image to Dockerhub?

### ISSUE THREAD

**Issue by manuschillerdev** [zgrossbart/jdd#51]
I love using jsondiff! It would be super convenient to just run `docker run -i --name jdd -p 127.0.0.1:8080:80/tcp jdd:v1-alpine
` and start it locally for sensible data.

For this to work, the image obviously must be available on a public registry like dockerhub.

Would you be willing to push the latest version there? Would be easier maintenance-wise if the maintainers did this, instead of someone from the community.

**Comment by zgrossbart** [comment]
That's a great idea @manuschillerdev.  I don't know why I didn't do it sooner. Let me see if I can find time for it this week.

**Comment by zgrossbart** [comment]
I've published the image to Docker Hub here:

https://hub.docker.com/repository/docker/zgrossbart/jsondiff

You should be able to run `docker run -i --name jdd -p 127.0.0.1:8080:80/tcp jdd:v1-alpine` without having to do the build step first.  Please try it out and let me know if you have any issues.

**Comment by manuschillerdev** [comment]
thanks! The image is available for me - I can start a fresh container via `docker run --name jdd --rm -p 8080:80 zgrossbart/jsondiff`

As a side note: it does not shut down via ctrl + r, though

**Comment by zgrossbart** [comment]
Thanks for trying it out.  I'm glad everything worked.  

The container not stopping when you press Ctrl+C is expected.  There's a good thread about it here:

https://stackoverflow.com/questions/41097652/how-to-fix-ctrlc-inside-a-docker-container#:~:text=Starting%20with%20docker%200.6.,C%20will%20terminate%20the%20container.

I've added instructions to the README about how to stop the container as well.
