### ISSUE TITLE
Removal of jQuery from jdd

### ISSUE THREAD

**Issue by gangadharjannu** [zgrossbart/jdd#56]
Hello @zgrossbart

I use jdd regularly and would like to know your opinion on removal of jQuery.

I am happy to work on PR if you are okay.

**Comment by zgrossbart** [comment]
Thank you @gangadharjannu.  I'm glad that JSONDiff is working well for you.  Can you please tell me more about why you want to remove jQuery.

**Comment by gangadharjannu** [comment]
There are multiple reasons, 

1. If we remove jQuery jdd will be pure JavaScript solution and it is easier for others to port this to other JavaScript frameworks like Angular or React (if they want).
2. Less size https://bundlephobia.com/package/jquery@3.7.0
3. Also no need to update frequently since there is no maintenance required for library update due to version changes or securities.
4. I'm sure there will be performance improvements as the proposed solution would be native to browser.
5. Browsers are more mature now and most of the DOM manipulation can be implement with pure JavaScript easily.

Let me know your thoughts/suggestions

**Comment by gangadharjannu** [comment]
@zgrossbart Here is the PR https://github.com/zgrossbart/jdd/pull/57.

All the functionality is converted to pure JavaScript. 

Let us discuss remaining things in the PR

**Comment by zgrossbart** [comment]
#57 is merged and this issue is resolved.
