### ISSUE TITLE
`null` values are not properly compared

### ISSUE THREAD

**Issue by richcocoa** [zgrossbart/jdd#7]
Diffs are not detected if the first JSON has a `null` value, but the second JSON has something else. Diffs are generated the other way around though.

An example:

Left JSON:
```json
{"a":null, "b":"xyz", "c":null}
```

Right JSON:
```json
{"a":null, "b":null, "c":123}
```

There are two diffs here, `"b"` and `"c"`. But only `"b"` is detected.

**Comment by zgrossbart** [comment]
I have merged in the pull request and done a tiny amount of cleanup.  This issue is now fixed.
